# Generated by Django 2.1.3 on 2018-11-25 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('summery', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_logo',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_name',
        ),
        migrations.AddField(
            model_name='movie',
            name='actor1',
            field=models.CharField(default='dharmendra', max_length=30),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor_movie1',
            field=models.CharField(default='some', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre1',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_logo1',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='file_type1',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='movie1',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='movie1.Movie'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_name1',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
